<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<DocumentationFile>$(OutputPath)$(AssemblyName).xml</DocumentationFile>
		<NoWarn>$(NoWarn);1591</NoWarn>
		<UserSecretsId>ca7925c4-e0a6-4234-88c0-c8254f9ab33e</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<DockerfileContext>..\..</DockerfileContext>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Project.Controller.Host\Project.Controller.Host.csproj" />
	</ItemGroup>

</Project>
