name: Docker Image CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  # Job 1: Build và Kiểm tra (CI)
  build-ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build
  
  # JOB 2: CD 
  push-to-ghcr:
    needs: build-ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: . # QUAN TRỌNG: Phải là gốc để thấy các project Core, Libs...
          file: Presentation/Project.Controller.Auth/Dockerfile # Đường dẫn đến Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/auth-service:latest
            ghcr.io/${{ github.repository_owner }}/auth-service:${{ github.sha }}
