name: Docker Image CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build
  
  push-to-ghcr:
    needs: build-ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # BƯỚC QUAN TRỌNG: Chuyển tên username thành chữ thường
      - name: Lowercase repository owner
        id: prep
        run: |
          echo "owner=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Presentation/Project.Controller.Auth/Dockerfile
          push: true
          # Sử dụng output từ bước 'prep' ở trên (đã được viết thường)
          tags: |
            ghcr.io/${{ steps.prep.outputs.owner }}/auth-service:latest
            ghcr.io/${{ steps.prep.outputs.owner }}/auth-service:${{ github.sha }}
